name: test

on: [push, pull_request]

jobs:
  bats-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS testing framework
        uses: mig4/setup-bats@v1.2.0
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Run BATS tests
        run: bats test/test.bats
